# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:10:11+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from starlette.requests import Request

from models import (
    EntitiesGetResponse,
    EntitiesGetResponse1,
    EntitiesPostResponse,
    EntitiesPostResponse1,
    ErrorCodesGetResponse,
    ErrorCodesGetResponse1,
    Lang,
)

app = MCPProxy(
    contact={'email': 'info@wealthreader.com'},
    description='Las APIs regulatorias basadas en PSD2 proporcionan acceso a cierta información financiera como saldos de cuentas bancarias y transacciones. Sin embargo, hay otras fuentes de información patrimonial que no son accesibles por estas APIs. La API de Wealth Reader amplía la información ofrecida por las APIs regulatorias proporcionando acceso en tiempo real a las fuentes patrimoniales adicionales en cualquier entidad del mundo. Existen otros dos documentos relacionados que te ayudarán a integrar la API de Wealth Reader. Uno es la guía de integración del widget Javascript: https://docs-es.wealthreader.com/, y el  otro una colección Postman basada en esta documentación.',
    title='Wealth Reader API',
    version='1.0.0',
    servers=[
        {
            'description': 'SwaggerHub API Auto Mocking',
            'url': 'https://virtserver.swaggerhub.com/Wealth-Reader/api/1.0.0',
        },
        {'description': '', 'url': 'https://api.wealthreader.com/'},
    ],
)


@app.get(
    '/entities',
    description=""" Obtiene el listado de entidades soportadas y la información necesaria para dibujar el formulario de login de la entidad.
 """,
    tags=['financial_entity_operations'],
)
def get_entities():
    """
    Obtiene el listado de entidades soportadas
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/entities',
    description=""" Obtiene los activos financieros y el detalle de su composición de carteras de inversión compuestas por acciones o fondos, tarjetas de crédito, seguros y préstamos. Incluye información de titularidad de cada uno de los activos así como identificadores únicos que facilitan el tratamiento del dato. Es posible obtener datos Mock. Consulte con el equipo técnico cómo hacerlo.
 """,
    tags=['financial_entity_operations'],
)
def post_entities(request: Request):
    """
    Obtiene los activos financieros y el detalle de su composición
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/error-codes',
    description=""" Listado de códigos de error. Presta especial atención a que no todos los códigos de error deben recibir el mismo tratamiento por parte de tu aplicación. Ante un error de password incorrecto no debes reintentar la llamada con los mismos parámetros, pero ante un error que te indique que la entidad está en mantenimiento sí puedes reintentarlo. Pide una sesión técnica con nuestro equipo para resolver cualquier duda sobre la gestión de errores.
 """,
    tags=['error_code_management'],
)
def get_error_codes(lang: Optional[Lang] = 'es'):
    """
    Listado de códigos de error
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
