# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:10:11+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import time
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Balances(BaseModel):
    available: Optional[float] = Field(None, examples=[14302.07])
    current: Optional[float] = Field(None, examples=[14302.07])


class Transaction(BaseModel):
    amount: Optional[float] = Field(None, examples=[-1.1])
    balance: Optional[float] = Field(None, examples=[14302.07])
    description: Optional[str] = Field(None, examples=['Pago en TELPARK MADRID ES'])
    operation_date: Optional[date_aliased] = Field(None, examples=['2022-12-30'])
    uuid: Optional[str] = Field(
        None, examples=['d0c2ea4c072cf4d7b0fd494d7728260d736e6b25']
    )
    value_date: Optional[date_aliased] = Field(None, examples=['2022-12-30'])


class Balances1(BaseModel):
    available: Optional[float] = Field(None, examples=[3980])
    disposed: Optional[float] = Field(None, examples=[20])
    limit: Optional[float] = Field(None, examples=[4000])


class Status(Enum):
    active = 'active'
    inactive = 'inactive'
    cancelled = 'cancelled'


class Subtype(Enum):
    credit = 'credit'
    debit = 'debit'
    prepaid = 'prepaid'


class Transactions(BaseModel):
    amount: float = Field(..., examples=[-20])
    description: str = Field(..., examples=['Pago en AMZN MKTP ES123CM0ZM4'])
    settled: Optional[bool] = Field(
        None,
        description='Indica si es un movimiento perteneciente a un extracto diferente del periodo de facturación actual',
        examples=[False],
    )
    uuid: str = Field(..., examples=['78ceedca9cd9d2f2bfbb2439795ab6a1fcefc12b'])
    value_date: date_aliased = Field(..., examples=['2022-12-28'])


class Contracts1(BaseModel):
    contract_id: str = Field(
        ...,
        description='Identificador único del contrato. Valor a indicar para seleccionar el contrato al que se desea acceder',
        examples=['B12345678'],
    )
    description: str = Field(
        ...,
        description='Descripción que acompaña al contract_id. Normalmente será el nombre de la sociedad o persona titular del contrato',
        examples=['WEALTH READER S.L.'],
    )


class Contracts(RootModel[Union[List[Dict[str, Any]], Contracts1]]):
    root: Union[List[Dict[str, Any]], Contracts1] = Field(
        ...,
        description='Solamente estará informado cuando el valor de code sea 2020 (usuario multicontrato)',
    )


class DocumentType(BaseModel):
    name: Optional[str] = Field(
        None,
        description="Nombre del campo. Al ser el campo 'tipo de documento' un listado de valores desplegables, este string es un listado de valores separados por punto y coma",
        examples=['DNI;Pasaporte'],
    )
    placeholder: Optional[str] = Field(
        None,
        description='Etiqueta dentro del campo que aporta información adicional sobre cómo rellenar la información',
        examples=[''],
    )
    required: Optional[bool] = Field(
        None, description='Indica si el campo es requerido', examples=[0]
    )
    validation_rule: Optional[str] = Field(
        None, description='Indica el tipo de dato que acepta este campo', examples=['']
    )


class Password(BaseModel):
    name: Optional[str] = Field(
        None, description='Nombre del campo', examples=['Clave de acceso']
    )
    placeholder: Optional[str] = Field(
        None,
        description='Etiqueta dentro del campo que aporta información adicional sobre cómo rellenar la información',
        examples=[''],
    )
    required: Optional[bool] = Field(
        None, description='Indica si el campo es requerido', examples=[1]
    )
    validation_rule: Optional[str] = Field(
        None,
        description='Indica el tipo de dato que acepta este campo',
        examples=["type='password'"],
    )


class SecondPassword(BaseModel):
    name: Optional[str] = Field(
        None, description='Indica el tipo de dato que acepta este campo', examples=['']
    )
    placeholder: Optional[str] = Field(
        None,
        description='Etiqueta dentro del campo que aporta información adicional sobre cómo rellenar la información',
        examples=[''],
    )
    required: Optional[bool] = Field(
        None, description='Indica si el campo es requerido', examples=[0]
    )
    validation_rule: Optional[str] = Field(
        None, description='The validation rule for the field', examples=['']
    )


class User(BaseModel):
    name: Optional[str] = Field(
        None, description='Nombre del campo', examples=['Nombre de usuario']
    )
    placeholder: Optional[str] = Field(
        None,
        description='Etiqueta dentro del campo que aporta información adicional sobre cómo rellenar la información',
        examples=['Email'],
    )
    required: Optional[bool] = Field(
        None, description='Indica si el campo es requerido', examples=[1]
    )
    validation_rule: Optional[str] = Field(
        None,
        description='Indica el tipo de dato que acepta este campo',
        examples=["type='email'"],
    )


class Inputs(BaseModel):
    document_type: Optional[DocumentType] = None
    password: Optional[Password] = None
    second_password: Optional[SecondPassword] = None
    user: Optional[User] = None


class ErrorCodes1(BaseModel):
    code: Optional[int] = Field(None, description='Código de error', examples=[2])
    description: Optional[str] = Field(
        None, description='Descripción del error', examples=['Llamada incorrecta']
    )
    how_to_proceed: Optional[str] = Field(
        None,
        description='Cómo actuar cuando se obtiene este código de error',
        examples=[
            'El texto recibido en "message" detallará el motivo del error. Por ejemplo, "El parámetro "api_key" es obligatorio".'
        ],
    )
    possible_reasons: Optional[str] = Field(
        None,
        description='Posibles causas del error',
        examples=[
            'Alguno de los parámetros requeridos no se ha enviado o se ha enviado en un formato incorrecto'
        ],
    )


class ErrorCodes(RootModel[Union[List[List], ErrorCodes1]]):
    root: Union[List[List], ErrorCodes1]


class ErrorDetail(BaseModel):
    code: int = Field(
        ...,
        description='El código indica la familia del error. Por ejemplo, de 2000 a 2999 indican problemas en el login. Cada código de error debe tratarse de forma diferente. Por ejemplo, si el código indica "Login incorrecto", no se debe reintentar la llamada; si el código indica "entidad en mantenimiento" sí se puede reintentar más tarde. Puedes obtener el listado completo en el método error-codes.',
        examples=[1000],
    )
    contracts: Optional[Contracts] = None
    message: str = Field(
        ...,
        description='Texto en el idioma de la entidad. Es seguro mostrárselo al usuario y en muchos casos le ayudará a corregir el error',
        examples=['Login incorrecto'],
    )


class Role(Enum):
    owner = 'owner'
    co_owner = 'co-owner'
    legal_representative = 'legal representative'
    administrator = 'administrator'
    attorney_in_fact = 'attorney-in-fact'
    authorised = 'authorised'


class Owner1(BaseModel):
    ID: str = Field(..., examples=['12345678Z'])
    name: str = Field(..., examples=['LUIS GARCIA BAQUERO'])
    role: Role = Field(..., examples=['owner'])


class Owner(RootModel[Union[List[List], Owner1]]):
    root: Union[List[List], Owner1]


class Composition(BaseModel):
    DGS: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: pension-plans',
        examples=['F0062'],
    )
    DGS_description: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: pension-plans',
        examples=['ABANCA EMPLEO, FONDO DE PENSIONES'],
    )
    ISIN: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: funds o stocks',
        examples=['ES0152743003'],
    )
    ISIN_description: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: funds o stocks',
        examples=['Fondo Dinámico'],
    )
    currency: Optional[str] = Field(
        None, description='Divisa en codificación ISO 4217', examples=['EUR']
    )
    price: Optional[float] = Field(
        None, description='Precio actual', examples=[14.5577]
    )
    shares: Optional[float] = Field(
        None, description='Participaciones', examples=[225.0077]
    )
    total_amount: Optional[float] = Field(
        None, description='Importe total', examples=[3275.6]
    )
    weighting: Optional[float] = Field(
        None,
        description='Peso con respecto al resto de la composición de la cartera',
        examples=[100],
    )


class Subtype1(Enum):
    funds = 'funds'
    stocks = 'stocks'
    pension_plans = 'pension-plans'


class OperationType(Enum):
    purchase = 'purchase'
    sale = 'sale'
    subscription_by_transfer = 'subscription by transfer'
    redemption_by_transfer = 'redemption by transfer'


class Transactions1(BaseModel):
    DGS: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: pension-plans',
        examples=['F0062'],
    )
    ISIN: Optional[str] = Field(
        None,
        description='Valor indicado siempre que la cartera sea subtype: funds o stocks',
        examples=['ES0152743003'],
    )
    currency: str = Field(..., examples=['EUR'])
    exchange_rate: float = Field(..., examples=[1])
    operation_date: Optional[date_aliased] = Field(None, examples=['2020-01-30'])
    operation_pending: Optional[bool] = Field(
        None,
        description='Indicado cuando subtype=stocks. Indica si la operación está pendiente o no de ejecutarse.',
        examples=[False],
    )
    operation_type: OperationType = Field(..., examples=['purchase'])
    price: float = Field(..., examples=[11.1438])
    reference_currency: str = Field(..., examples=['EUR'])
    shares: float = Field(..., examples=[1076.8273])
    total_amount: float = Field(..., examples=[12000])
    uuid: str = Field(
        ...,
        description='Identificador único asignado por Wealth Reader',
        examples=['05e4563f5bbf2d06efd0a29ebe7edbbb4e1bff63'],
    )
    value_date: date_aliased = Field(..., examples=['2020-01-30'])
    value_time: Optional[time] = Field(
        None,
        description='Indicado cuando subtype=stocks. La hora de ejecución de la operación.',
        examples=['09:00'],
    )


class Portfolios1(BaseModel):
    annualized_volatility: float = Field(
        ...,
        description='El valor será 0 cuando la entidad no lo proporcione',
        examples=[0],
    )
    code: str = Field(..., examples=['1465010091400123456789'])
    composition: Union[List[Dict[str, Any]], Composition] = Field(
        ..., description='Composición de la cartera'
    )
    contracting_date: date_aliased = Field(..., examples=['2016-04-27'])
    contributions: float = Field(..., examples=[3019.33])
    currency: str = Field(..., examples=['EUR'])
    linked_account: str = Field(
        ...,
        description='Código IBAN sin espacios. El valor será not-provided cuando la entidad no lo proporcione',
        examples=['ES4021005321592566566159'],
    )
    name: str = Field(..., examples=['Fondo Dinámico'])
    owners: Owner
    subtype: Subtype1 = Field(..., examples=['funds'])
    total_value: float = Field(..., examples=[3275.6])
    transactions: Union[List[Dict[str, Any]], Transactions1]
    uuid: str = Field(
        ...,
        description='Identificador único asignado por Wealth Reader',
        examples=['05e4563f5bbf2d06efd0a29ebe7edbbb4e1bff63'],
    )
    weighted_return: float = Field(..., examples=[8.49])
    withholdings: float = Field(..., examples=[0])
    yield_: float = Field(..., alias='yield', examples=[256.27])


class Portfolios(RootModel[Union[List[Dict[str, Any]], Portfolios1]]):
    root: Union[List[Dict[str, Any]], Portfolios1] = Field(
        ..., description='Carteras de acciones, fondos y planes de pensiones'
    )


class HistoricPrice(BaseModel):
    date: Optional[date_aliased] = None
    price: Optional[float] = None


class Properties(BaseModel):
    code: str = Field(..., description='Referencia catastral')
    currency: str
    description: Optional[str] = None
    historic_prices: List[HistoricPrice]
    purpose: Optional[str] = None
    trading_price: float
    trading_year: float
    uuid: str


class Statistics(BaseModel):
    SESSION: str = Field(
        ...,
        description='Guarda siempre este valor, tanto si la conexión es correcta como si no. Es necesario para obtener soporte',
        examples=['3463754e3540884'],
    )
    execution_time: float = Field(
        ..., description='Duración de la ejecución', examples=[0.958119869232178]
    )
    operation_id: Optional[str] = Field(
        None,
        description='El valor vendrá indicado cuando se haya invocado a la API a través del Widget que proporciona Wealth Reader. Para saber más sobre este tipo de integración, visita: https://docs-es.wealthreader.com/',
        examples=['1827C79229'],
    )
    token: Optional[str] = Field(
        None,
        description='El valor vendrá indicado cuando se ha pedido la custodia de credenciales con la opción tokenize=true',
        examples=['FRJ0mHlaqZwLzu'],
    )


class Gender(Enum):
    male = 'male'
    female = 'female'


class MaritalStatus(Enum):
    single = 'single'
    married = 'married'


class UserInformation(BaseModel):
    ID: str = Field(..., examples=['12345678Z'])
    address: Optional[str] = Field(None, examples=['CALLE BAILEN 41 1A'])
    birth_date: Optional[date_aliased] = Field(None, examples=['1980-09-26'])
    birth_place: Optional[str] = Field(None, examples=['SEVILLA'])
    cell_phone: Optional[str] = Field(
        None,
        description='Número de teléfono con el prefijo internacional, sin espacios',
        examples=['+34666123456'],
    )
    city: Optional[str] = Field(None, examples=['MADRID'])
    country: Optional[str] = Field(None, examples=['SPAIN'])
    email: Optional[str] = Field(None, examples=['lgarcia@gmail.com'])
    gender: Optional[Gender] = Field(None, examples=['male'])
    job: Optional[str] = Field(
        None,
        description='El valor aquí es muy variable de una entidad a otra: de indicar solamente si es cuenta propia o cuenta ajena a indicar el tipo de profesión',
        examples=['CUENTA PROPIA'],
    )
    marital_status: Optional[MaritalStatus] = Field(None, examples=['married'])
    name: str = Field(..., examples=['LUIS GARCIA BAQUERO'])
    postal_code: Optional[str] = Field(None, examples=['28005'])


class DocumentType1(Enum):
    NIF = 'NIF'
    Pasaporte = 'Pasaporte'
    Tarjeta_de_residencia = 'Tarjeta de residencia'


class EntitiesPostRequest(BaseModel):
    OTP: Optional[str] = Field(
        None,
        description='Solo necesario cuando se esté completando la seguda petición de un login con 2 factores de autenticación, si el tipo de desafío es OTP. Requiere la clave que la entidad le ha enviado al usario final',
    )
    SESSION: Optional[str] = Field(
        None,
        description='Solo necesario cuando se esté completando la seguda petición de un login con 2 factores de autenticación. Requiere el valor de SESSION obtenido en la primera petición',
    )
    api_key: Optional[str] = Field(
        None, description='Identifica al cliente en el servicio'
    )
    code: Optional[str] = Field(
        None,
        description='Nombre de la entidad. El listado completo está disponible con GET',
    )
    contract_code: Optional[str] = Field(
        None,
        description='Solo necesario cuando el usuario puede acceder a más de un contrato. El listado de contratos disponibles se obtiene al realizar una conexión con un usuario con opción a trabajar con varios contratos en su entidad (que al hacer login en su banca online ve como primera opción una pantalla de selección de contratos) y cuya llamada a la API no se le ha especificado un valor a contract_code',
    )
    document_type: Optional[DocumentType1] = Field(
        None,
        description='Tipo de documento, requerido según la entidad. Si es requerido o no, está indicado en el listado de entidades. Ver definición.',
        examples=['NIF'],
    )
    password: Optional[str] = Field(None, description='Contraseña')
    second_password: Optional[str] = Field(
        None, description='Segunda contraseña, requerida según la entidad.'
    )
    token: Optional[str] = Field(
        None,
        description='Valor para credenciales custodiadas, tokenizadas previamente mediante una llamada a este método con el valor de tokenize=true. Están disponibles los siguientes usuarios Mock: MOCKDATA, respuesta OK; MOCKOTP, respuesta con desafío OTP; MOCKLOGINKO, respuesta con error de login',
    )
    tokenize: Optional[bool] = Field(
        False,
        description='Indica si Wealth Reader debe custodiar los credenciales, de tal manera que incluído en el body de respuesta estará un token que permite conectar con la entidad sin necesidad de conocer los credenciales: document_type, user, password, second_password, contract_code',
    )
    user: Optional[str] = Field(
        None,
        description='Usuario. Están disponibles los siguientes usuarios Mock: MOCKDATA, respuesta OK; MOCKOTP, respuesta con desafío OTP; MOCKLOGINKO, respuesta con error de login',
    )


class Lang(Enum):
    es = 'es'
    en = 'en'


class ErrorCodesGetResponse(RootModel[List[ErrorCodes]]):
    root: List[ErrorCodes]


class Accounts1(BaseModel):
    balances: Balances
    code: str = Field(
        ...,
        description='Código IBAN sin espacios',
        examples=['ES4914651234561234567890'],
    )
    currency: str = Field(..., examples=['EUR'])
    name: str = Field(..., examples=['Cuenta NÓMINA'])
    owners: Owner
    transactions: List[Transaction]
    uuid: str = Field(..., examples=['8076932f04f73e27fe608fee4d12fca8708dec8c'])


class Accounts(RootModel[Union[List[Dict[str, Any]], Accounts1]]):
    root: Union[List[Dict[str, Any]], Accounts1] = Field(
        ...,
        description='Cuentas bancarias. En cuentas europeas, solamente activado cuando el cliente de Wealth Reader cuenta con licencia PSD2',
    )


class Cards1(BaseModel):
    anual_interest: Optional[float] = Field(None, examples=[17.48])
    balances: Balances1
    code: str = Field(
        ...,
        description='Numeración con ofuscación PCI compliance',
        examples=['516097********1234'],
    )
    currency: str = Field(..., examples=['EUR'])
    linked_account: Optional[str] = Field(None, examples=['ES4021005321592566566159'])
    name: str = Field(..., examples=['Tarjeta Crédito'])
    next_payment_date: Optional[date_aliased] = Field(None, examples=['2023-01-05'])
    owner: Optional[Owner] = None
    status: Optional[Status] = Field(None, examples=['active'])
    subtype: Subtype = Field(..., examples=['credit'])
    tae: Optional[float] = Field(None, examples=[18.95])
    transactions: Optional[Union[List[Dict[str, Any]], Transactions]] = None
    uuid: str = Field(..., examples=['aefd89eade0a6a09d9b8eab4c22da6a6a37632e6'])


class Cards(RootModel[Union[List[Dict[str, Any]], Cards1]]):
    root: Union[List[Dict[str, Any]], Cards1] = Field(
        ..., description='Tarjetas de crédito, débito y prepago'
    )


class Entities1(BaseModel):
    bic: Optional[str] = Field(
        None,
        description='Código BIC. Solamente está indicado cuando la entidad es un banco',
        examples=['BMARES2M'],
    )
    code: str = Field(
        ..., description='El código de la institución', examples=['bancamarch']
    )
    inputs: Inputs
    logo: str = Field(
        ...,
        description='Logotipo',
        examples=['https://cdn.wealthreader.com/bancamarch.svg'],
    )
    name: str = Field(
        ..., description='The nombre de la institución', examples=['Bancamarch']
    )
    statistics: Optional[Statistics] = None


class Entities(RootModel[Union[List[Dict[str, Any]], Entities1]]):
    root: Union[List[Dict[str, Any]], Entities1]


class Payload(BaseModel):
    accounts: Optional[Accounts] = None
    cards: Optional[Cards] = None
    portfolios: Optional[Portfolios] = None
    properties: Optional[Properties] = None
    user_information: Optional[UserInformation] = None


class EntityData1(BaseModel):
    payload: Optional[Payload] = None
    statistics: Statistics
    success: bool = Field(..., examples=[True])
    portfolios: Optional[List] = None


class EntityData2(BaseModel):
    payload: Optional[Payload] = None
    statistics: Statistics
    success: bool = Field(..., examples=[True])
    accounts: Optional[List] = None


class EntityData3(BaseModel):
    payload: Optional[Payload] = None
    statistics: Statistics
    success: bool = Field(..., examples=[True])
    cards: Optional[List] = None


class EntityData4(BaseModel):
    payload: Optional[Payload] = None
    statistics: Statistics
    success: bool = Field(..., examples=[True])
    properties: Optional[List] = None


class EntityData(RootModel[Union[EntityData1, EntityData2, EntityData3, EntityData4]]):
    root: Union[EntityData1, EntityData2, EntityData3, EntityData4]


class Error(BaseModel):
    error: ErrorDetail
    statistics: Statistics
    success: bool = Field(..., examples=[False])


class EntitiesGetResponse(RootModel[List[Entities]]):
    root: List[Entities]


class EntitiesGetResponse1(RootModel[List[Error]]):
    root: List[Error]


class EntitiesPostResponse(RootModel[List[EntityData]]):
    root: List[EntityData]


class EntitiesPostResponse1(RootModel[List[Error]]):
    root: List[Error]


class ErrorCodesGetResponse1(RootModel[List[Error]]):
    root: List[Error]
